### ISSUE TITLE
Same project here 

### ISSUE THREAD

**Issue by postite** [PRASS95/TweenMaxHaxeJS#1]
Hello , it´s funny .i've started an extern port yesterday for greensock gsap too !
Have a look here https://github.com/postite/GSAP
There are some slighlty differences .
It's also not finished yet.
By the way .. Why do you provide an array access for tweenmax ?.

**Comment by PRASS95** [comment]
Salut,

(oui je me suis aperçu que tu étais français :D)

Depuis le temps que je me tâtais à faire cet extern, c'est assez fou.
Tu es beaucoup plus avancé que moi dans le coverage de la lib, je vois plus trop l'intérêt pour moi de continuer :(
Pour TweenMax et son ArrayAccess, c'est soit une erreur de ma part, soit un relicat de mes 1ers tests.

A+

**Comment by postite** [comment]
quoi j'ai un accent français quand j'ecris ?
j'ai updaté un peu en bougeant les plugins .... et separé les fichiers pour n'importer les lib JS qu'au besoin .
du coup j'ai du virer l'heritage ... c'est mouof ! mais bon ...
si tu t'en sers et que tu trouve des trucs .. n'hesites pas !
